// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // db push / migrate 等のCLI操作はDDL・アドバイザリロックを使うため、
    // PgBouncerのトランザクションプーリング接続(DATABASE_URL)ではなく
    // 直接接続(DIRECT_URL)を使う。アプリ実行時の接続は lib/prisma.ts が
    // DATABASE_URL を直接参照しており、ここには影響しない。
    url: process.env['DIRECT_URL'],
  },
});
