drop trigger if exists "update_rooms_updated_at" on "public"."rooms";

revoke delete on table "public"."users" from "anon";

revoke insert on table "public"."users" from "anon";

revoke references on table "public"."users" from "anon";

revoke select on table "public"."users" from "anon";

revoke trigger on table "public"."users" from "anon";

revoke truncate on table "public"."users" from "anon";

revoke update on table "public"."users" from "anon";

revoke delete on table "public"."users" from "authenticated";

revoke insert on table "public"."users" from "authenticated";

revoke references on table "public"."users" from "authenticated";

revoke select on table "public"."users" from "authenticated";

revoke trigger on table "public"."users" from "authenticated";

revoke truncate on table "public"."users" from "authenticated";

revoke update on table "public"."users" from "authenticated";

revoke delete on table "public"."users" from "service_role";

revoke insert on table "public"."users" from "service_role";

revoke references on table "public"."users" from "service_role";

revoke select on table "public"."users" from "service_role";

revoke trigger on table "public"."users" from "service_role";

revoke truncate on table "public"."users" from "service_role";

revoke update on table "public"."users" from "service_role";

alter table "public"."rooms" drop constraint "rooms_status_check";

drop function if exists "public"."update_updated_at_column"();

alter table "public"."users" drop constraint "users_pkey";

drop index if exists "public"."idx_users_username";

drop index if exists "public"."users_pkey";

drop table "public"."users";


  create table "public"."answer_inputs" (
    "text" text,
    "result" text,
    "created_at" timestamp with time zone not null default now(),
    "room_id" uuid not null
      );


alter table "public"."answer_inputs" enable row level security;


  create table "public"."history_drawings" (
    "id" uuid not null default gen_random_uuid(),
    "room_id" uuid,
    "user_id" uuid,
    "canvas_data" jsonb,
    "element_count" bigint,
    "created_at" timestamp with time zone,
    "theme" text,
    "deleted_at" timestamp(6) with time zone
      );


alter table "public"."history_drawings" enable row level security;


  create table "public"."m_user" (
    "id" uuid not null,
    "username" text,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "deleted_at" timestamp(6) with time zone,
    "icon_name" text default 'TbBallBowling'::text,
    "icon_color" text default '#000000'::text
      );


alter table "public"."m_user" enable row level security;


  create table "public"."points" (
    "id" uuid not null default gen_random_uuid(),
    "room_id" uuid not null,
    "user_id" uuid,
    "point" smallint,
    "deleted_at" timestamp(6) with time zone
      );


alter table "public"."points" enable row level security;


  create table "public"."subscriptions" (
    "id" uuid not null default gen_random_uuid(),
    "user_id" uuid not null,
    "subscription" jsonb not null,
    "created_at" timestamp with time zone default now(),
    "room_id" uuid not null,
    "deleted_at" timestamp(6) with time zone
      );


alter table "public"."subscriptions" enable row level security;


  create table "public"."theme" (
    "id" bigint generated by default as identity not null,
    "theme" text not null,
    "level" text default 'nomal'::text,
    "kanji" text,
    "katakana" text,
    "furigana" text,
    "genre" text not null default 'ランダム'::text
      );


alter table "public"."theme" enable row level security;

alter table "public"."drawings" add column "deleted_at" timestamp(6) with time zone;

alter table "public"."drawings" add column "theme" text;

alter table "public"."drawings" alter column "created_at" set default timezone('utc'::text, now());

alter table "public"."drawings" alter column "created_at" set not null;

alter table "public"."drawings" enable row level security;

alter table "public"."rooms" drop column "answerer_id";

alter table "public"."rooms" drop column "updated_at";

alter table "public"."rooms" add column "answer_id" uuid;

alter table "public"."rooms" add column "created_by_userId" uuid;

alter table "public"."rooms" add column "current_theme_id" smallint;

alter table "public"."rooms" add column "deleted_at" timestamp(6) with time zone;

alter table "public"."rooms" add column "genre" text;

alter table "public"."rooms" add column "level" text;

alter table "public"."rooms" add column "room_name" text not null;

alter table "public"."rooms" add column "short_id" text not null;

alter table "public"."rooms" alter column "created_at" set default timezone('utc'::text, now());

alter table "public"."rooms" alter column "created_at" set not null;

alter table "public"."rooms" alter column "status" drop not null;

alter table "public"."rooms" enable row level security;

CREATE UNIQUE INDEX answer_inputs_pkey ON public.answer_inputs USING btree (room_id);

CREATE INDEX drawings_deleted_at_idx ON public.drawings USING btree (deleted_at);

CREATE INDEX history_drawings_deleted_at_idx ON public.history_drawings USING btree (deleted_at);

CREATE INDEX history_drawings_element_count_idx ON public.history_drawings USING btree (element_count);

CREATE UNIQUE INDEX history_drawings_pkey ON public.history_drawings USING btree (id);

CREATE INDEX history_drawings_theme_idx ON public.history_drawings USING btree (theme);

CREATE INDEX m_user_deleted_at_idx ON public.m_user USING btree (deleted_at);

CREATE UNIQUE INDEX m_user_pkey ON public.m_user USING btree (id);

CREATE INDEX points_deleted_at_idx ON public.points USING btree (deleted_at);

CREATE UNIQUE INDEX points_pkey ON public.points USING btree (id);

CREATE INDEX rooms_deleted_at_idx ON public.rooms USING btree (deleted_at);

CREATE UNIQUE INDEX rooms_short_id_key ON public.rooms USING btree (short_id);

CREATE INDEX subscriptions_deleted_at_idx ON public.subscriptions USING btree (deleted_at);

CREATE UNIQUE INDEX subscriptions_pkey ON public.subscriptions USING btree (id);

CREATE UNIQUE INDEX subscriptions_user_id_key ON public.subscriptions USING btree (user_id);

CREATE UNIQUE INDEX theme_pkey ON public.theme USING btree (id);

alter table "public"."answer_inputs" add constraint "answer_inputs_pkey" PRIMARY KEY using index "answer_inputs_pkey";

alter table "public"."history_drawings" add constraint "history_drawings_pkey" PRIMARY KEY using index "history_drawings_pkey";

alter table "public"."m_user" add constraint "m_user_pkey" PRIMARY KEY using index "m_user_pkey";

alter table "public"."points" add constraint "points_pkey" PRIMARY KEY using index "points_pkey";

alter table "public"."subscriptions" add constraint "subscriptions_pkey" PRIMARY KEY using index "subscriptions_pkey";

alter table "public"."theme" add constraint "theme_pkey" PRIMARY KEY using index "theme_pkey";

alter table "public"."answer_inputs" add constraint "answer_inputs_text_check" CHECK ((length(text) < 30)) not valid;

alter table "public"."answer_inputs" validate constraint "answer_inputs_text_check";

alter table "public"."drawings" add constraint "fk_drawings_user_id" FOREIGN KEY (user_id) REFERENCES public.m_user(id) ON DELETE CASCADE not valid;

alter table "public"."drawings" validate constraint "fk_drawings_user_id";

alter table "public"."history_drawings" add constraint "fk_history_drawings_user_id" FOREIGN KEY (user_id) REFERENCES public.m_user(id) ON DELETE CASCADE not valid;

alter table "public"."history_drawings" validate constraint "fk_history_drawings_user_id";

alter table "public"."points" add constraint "fk_points_user_id" FOREIGN KEY (user_id) REFERENCES public.m_user(id) ON DELETE CASCADE not valid;

alter table "public"."points" validate constraint "fk_points_user_id";

alter table "public"."rooms" add constraint "fk_rooms_answer_id" FOREIGN KEY (answer_id) REFERENCES public.m_user(id) ON DELETE SET NULL not valid;

alter table "public"."rooms" validate constraint "fk_rooms_answer_id";

alter table "public"."rooms" add constraint "fk_rooms_created_by_userid" FOREIGN KEY ("created_by_userId") REFERENCES public.m_user(id) ON DELETE SET NULL not valid;

alter table "public"."rooms" validate constraint "fk_rooms_created_by_userid";

alter table "public"."rooms" add constraint "rooms_short_id_key" UNIQUE using index "rooms_short_id_key";

alter table "public"."subscriptions" add constraint "fk_subscriptions_user_id" FOREIGN KEY (user_id) REFERENCES public.m_user(id) ON DELETE CASCADE not valid;

alter table "public"."subscriptions" validate constraint "fk_subscriptions_user_id";

alter table "public"."subscriptions" add constraint "subscriptions_user_id_key" UNIQUE using index "subscriptions_user_id_key";

alter table "public"."rooms" add constraint "rooms_status_check" CHECK ((status = ANY (ARRAY['WAITING'::text, 'DRAWING'::text, 'ANSWERING'::text, 'RESULT'::text, 'FINISHED'::text, 'RESETTING'::text]))) not valid;

alter table "public"."rooms" validate constraint "rooms_status_check";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.copy_to_history_drawings()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$begin
      insert into history_drawings (room_id,user_id,canvas_data,element_count,created_at,theme)
      values (NEW.room_id, NEW.user_id, NEW.canvas_data, NEW.element_count, NEW.created_at, NEW.theme);
      RETURN NEW;
    end;$function$
;

grant delete on table "public"."answer_inputs" to "anon";

grant insert on table "public"."answer_inputs" to "anon";

grant references on table "public"."answer_inputs" to "anon";

grant select on table "public"."answer_inputs" to "anon";

grant trigger on table "public"."answer_inputs" to "anon";

grant truncate on table "public"."answer_inputs" to "anon";

grant update on table "public"."answer_inputs" to "anon";

grant delete on table "public"."answer_inputs" to "authenticated";

grant insert on table "public"."answer_inputs" to "authenticated";

grant references on table "public"."answer_inputs" to "authenticated";

grant select on table "public"."answer_inputs" to "authenticated";

grant trigger on table "public"."answer_inputs" to "authenticated";

grant truncate on table "public"."answer_inputs" to "authenticated";

grant update on table "public"."answer_inputs" to "authenticated";

grant delete on table "public"."answer_inputs" to "service_role";

grant insert on table "public"."answer_inputs" to "service_role";

grant references on table "public"."answer_inputs" to "service_role";

grant select on table "public"."answer_inputs" to "service_role";

grant trigger on table "public"."answer_inputs" to "service_role";

grant truncate on table "public"."answer_inputs" to "service_role";

grant update on table "public"."answer_inputs" to "service_role";

grant delete on table "public"."history_drawings" to "anon";

grant insert on table "public"."history_drawings" to "anon";

grant references on table "public"."history_drawings" to "anon";

grant select on table "public"."history_drawings" to "anon";

grant trigger on table "public"."history_drawings" to "anon";

grant truncate on table "public"."history_drawings" to "anon";

grant update on table "public"."history_drawings" to "anon";

grant delete on table "public"."history_drawings" to "authenticated";

grant insert on table "public"."history_drawings" to "authenticated";

grant references on table "public"."history_drawings" to "authenticated";

grant select on table "public"."history_drawings" to "authenticated";

grant trigger on table "public"."history_drawings" to "authenticated";

grant truncate on table "public"."history_drawings" to "authenticated";

grant update on table "public"."history_drawings" to "authenticated";

grant delete on table "public"."history_drawings" to "service_role";

grant insert on table "public"."history_drawings" to "service_role";

grant references on table "public"."history_drawings" to "service_role";

grant select on table "public"."history_drawings" to "service_role";

grant trigger on table "public"."history_drawings" to "service_role";

grant truncate on table "public"."history_drawings" to "service_role";

grant update on table "public"."history_drawings" to "service_role";

grant delete on table "public"."m_user" to "anon";

grant insert on table "public"."m_user" to "anon";

grant references on table "public"."m_user" to "anon";

grant select on table "public"."m_user" to "anon";

grant trigger on table "public"."m_user" to "anon";

grant truncate on table "public"."m_user" to "anon";

grant update on table "public"."m_user" to "anon";

grant delete on table "public"."m_user" to "authenticated";

grant insert on table "public"."m_user" to "authenticated";

grant references on table "public"."m_user" to "authenticated";

grant select on table "public"."m_user" to "authenticated";

grant trigger on table "public"."m_user" to "authenticated";

grant truncate on table "public"."m_user" to "authenticated";

grant update on table "public"."m_user" to "authenticated";

grant delete on table "public"."m_user" to "service_role";

grant insert on table "public"."m_user" to "service_role";

grant references on table "public"."m_user" to "service_role";

grant select on table "public"."m_user" to "service_role";

grant trigger on table "public"."m_user" to "service_role";

grant truncate on table "public"."m_user" to "service_role";

grant update on table "public"."m_user" to "service_role";

grant delete on table "public"."points" to "anon";

grant insert on table "public"."points" to "anon";

grant references on table "public"."points" to "anon";

grant select on table "public"."points" to "anon";

grant trigger on table "public"."points" to "anon";

grant truncate on table "public"."points" to "anon";

grant update on table "public"."points" to "anon";

grant delete on table "public"."points" to "authenticated";

grant insert on table "public"."points" to "authenticated";

grant references on table "public"."points" to "authenticated";

grant select on table "public"."points" to "authenticated";

grant trigger on table "public"."points" to "authenticated";

grant truncate on table "public"."points" to "authenticated";

grant update on table "public"."points" to "authenticated";

grant delete on table "public"."points" to "service_role";

grant insert on table "public"."points" to "service_role";

grant references on table "public"."points" to "service_role";

grant select on table "public"."points" to "service_role";

grant trigger on table "public"."points" to "service_role";

grant truncate on table "public"."points" to "service_role";

grant update on table "public"."points" to "service_role";

grant delete on table "public"."subscriptions" to "anon";

grant insert on table "public"."subscriptions" to "anon";

grant references on table "public"."subscriptions" to "anon";

grant select on table "public"."subscriptions" to "anon";

grant trigger on table "public"."subscriptions" to "anon";

grant truncate on table "public"."subscriptions" to "anon";

grant update on table "public"."subscriptions" to "anon";

grant delete on table "public"."subscriptions" to "authenticated";

grant insert on table "public"."subscriptions" to "authenticated";

grant references on table "public"."subscriptions" to "authenticated";

grant select on table "public"."subscriptions" to "authenticated";

grant trigger on table "public"."subscriptions" to "authenticated";

grant truncate on table "public"."subscriptions" to "authenticated";

grant update on table "public"."subscriptions" to "authenticated";

grant delete on table "public"."subscriptions" to "service_role";

grant insert on table "public"."subscriptions" to "service_role";

grant references on table "public"."subscriptions" to "service_role";

grant select on table "public"."subscriptions" to "service_role";

grant trigger on table "public"."subscriptions" to "service_role";

grant truncate on table "public"."subscriptions" to "service_role";

grant update on table "public"."subscriptions" to "service_role";

grant delete on table "public"."theme" to "anon";

grant insert on table "public"."theme" to "anon";

grant references on table "public"."theme" to "anon";

grant select on table "public"."theme" to "anon";

grant trigger on table "public"."theme" to "anon";

grant truncate on table "public"."theme" to "anon";

grant update on table "public"."theme" to "anon";

grant delete on table "public"."theme" to "authenticated";

grant insert on table "public"."theme" to "authenticated";

grant references on table "public"."theme" to "authenticated";

grant select on table "public"."theme" to "authenticated";

grant trigger on table "public"."theme" to "authenticated";

grant truncate on table "public"."theme" to "authenticated";

grant update on table "public"."theme" to "authenticated";

grant delete on table "public"."theme" to "service_role";

grant insert on table "public"."theme" to "service_role";

grant references on table "public"."theme" to "service_role";

grant select on table "public"."theme" to "service_role";

grant trigger on table "public"."theme" to "service_role";

grant truncate on table "public"."theme" to "service_role";

grant update on table "public"."theme" to "service_role";


  create policy "answer_inputs_policy"
  on "public"."answer_inputs"
  as permissive
  for all
  to public
using (true);



  create policy "Allow public access to drawings"
  on "public"."drawings"
  as permissive
  for all
  to public
using (true);



  create policy "history_drawing_policy"
  on "public"."history_drawings"
  as permissive
  for all
  to public
using (true);



  create policy "points_by_room"
  on "public"."points"
  as permissive
  for all
  to public
using (true);



  create policy "Allow public access to rooms"
  on "public"."rooms"
  as permissive
  for all
  to public
using (true);



  create policy "subscription_policy"
  on "public"."subscriptions"
  as permissive
  for all
  to public
using (true);



  create policy "Allow public access to theme"
  on "public"."theme"
  as permissive
  for select
  to public
using (true);


CREATE TRIGGER copy_to_history_trigger AFTER INSERT OR UPDATE ON public.drawings FOR EACH ROW EXECUTE FUNCTION public.copy_to_history_drawings();

-- 本番専用のwebPush-webhookトリガー(service_roleキー埋め込み)はローカル環境では意図的に作成しない。
-- ローカルでdrawingsにINSERTしても本番のsend-push Edge Functionが呼ばれないようにするため。

-- storageスキーマ内部トリガー(objects/prefixes/protect_delete)は、
-- ローカルSupabase CLIのstorage-apiイメージのバージョンが古く対応関数が無いため除外。
-- public スキーマのアプリデータには影響しない。


